package com.wfcimoveis.wfcsystem;

import java.nio.file.*;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import java.util.Base64;
import java.security.MessageDigest;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

/** Banco local offline; não armazena senhas de infraestrutura. */
final class AppDatabase implements AutoCloseable {
  record RecordRow(String type, String id, String payload, long version) {}
  record UserRow(String username, String fullName, String profile, boolean active, String email, String creci) {}
  record ImageRow(long id, String category, String entityId, String originalName, String stagedPath) {}
  private final Connection connection;
  private final Path path;

  AppDatabase() throws SQLException {
    try { Class.forName("org.sqlite.JDBC"); } catch (ClassNotFoundException e) { throw new SQLException("Driver SQLite ausente", e); }
    try {
      Path dir=Path.of(System.getProperty("user.home"),".wfcsystem"); Files.createDirectories(dir); path=dir.resolve("wfcsystem.db");
      connection=DriverManager.getConnection("jdbc:sqlite:"+path); connection.setAutoCommit(true);
      try(Statement s=connection.createStatement()) {
        s.execute("PRAGMA foreign_keys=ON"); s.execute("PRAGMA journal_mode=WAL");
        s.execute("CREATE TABLE IF NOT EXISTS app_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)");
        s.execute("CREATE TABLE IF NOT EXISTS local_records (entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, payload_json TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL, deleted INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(entity_type,entity_id))");
        s.execute("CREATE TABLE IF NOT EXISTS sync_queue (id INTEGER PRIMARY KEY AUTOINCREMENT, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, operation TEXT NOT NULL, payload_json TEXT NOT NULL, base_version INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'PENDING', error_message TEXT, created_at TEXT NOT NULL, synced_at TEXT)");
        s.execute("CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON sync_queue(status,id)");
        s.execute("CREATE TABLE IF NOT EXISTS app_users (username TEXT PRIMARY KEY, full_name TEXT NOT NULL, cpf TEXT NOT NULL, email TEXT NOT NULL, whatsapp TEXT NOT NULL, profile TEXT NOT NULL, creci TEXT, salt_b64 TEXT NOT NULL, hash_b64 TEXT NOT NULL, iterations INTEGER NOT NULL, active INTEGER NOT NULL DEFAULT 1, must_change_password INTEGER NOT NULL DEFAULT 1)");
        s.execute("CREATE TABLE IF NOT EXISTS image_queue (id INTEGER PRIMARY KEY AUTOINCREMENT, category TEXT NOT NULL, entity_id TEXT NOT NULL, original_name TEXT NOT NULL, staged_path TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING', error_message TEXT, created_at TEXT NOT NULL, uploaded_at TEXT)");
        s.execute("CREATE INDEX IF NOT EXISTS idx_image_queue_status ON image_queue(status,id)");
      }
      seedUsers();
    } catch(Exception e) { throw new SQLException("Não foi possível abrir o banco local",e); }
  }
  synchronized Path path(){return path;}
  private void seedUsers() throws SQLException { String q="INSERT OR IGNORE INTO app_users(username,full_name,cpf,email,whatsapp,profile,creci,salt_b64,hash_b64,iterations) VALUES(?,?,?,?,?,?,?,?,?,?)"; Object[][] u={{"wellington.wfc","Wellington Flavio Oliveira de Carvalho","975.886.101-82","wellington.corretor@wfcimoveis.com","(62) 99309-9184","Corretor","21496","G4kJ07OcUwOwi6/Li0eL+Q==","3ZT/65I5Id7CZ5wlHjZAxkMhKM8cP4SIBB6X/vlUH4g=",150000},{"wesley.wfc","Wesley Oliveira de Carvalho","007.359.671-05","wesley.corretor@wfcimoveis.com","(62) 99234-5819","Corretor","42716","3b3LW+lVyNeqd84Gk6Mykw==","cCL6tlI+R65OxmD92Ps9YowJyJ1RWXJpJIH9sE3Ko1c=",150000},{"eduarda.wfc","Eduarda Oliveira da Silva","078.875.521-84","duda.atendimento@wfcimoveis.com","(61) 99922-7042","Atendimento","","pozhgZvFnSbL/x3kcJ3T4w==","yp+TWu0qOhVB4TFRsPAKFEGa35AU8oq3//M3SippI9I=",150000},{"rodrigo.wfc","Rodrigo Honório da Silva","002.442.211-89","rodrigo.suporte@wfcimoveis.com","(64) 99272-0965","Administrador","","TJ4Lsm4embFkb5G7ioACtA==","nN/OpAxAmQbByw8f1oOr+egEz2DJHzS6RbXUX07sEjw=",150000}}; try(PreparedStatement p=connection.prepareStatement(q)){for(Object[] row:u){for(int i=0;i<row.length;i++)p.setObject(i+1,row[i]);p.executeUpdate();}}
  }
  synchronized String authenticateLocal(String username,char[] password)throws Exception{String q="SELECT full_name,profile,salt_b64,hash_b64,iterations,active FROM app_users WHERE username=?";try(PreparedStatement p=connection.prepareStatement(q)){p.setString(1,username);try(ResultSet r=p.executeQuery()){if(!r.next()||r.getInt(6)!=1)return null;byte[] salt=Base64.getDecoder().decode(r.getString(3)),expected=Base64.getDecoder().decode(r.getString(4));PBEKeySpec spec=new PBEKeySpec(password,salt,r.getInt(5),256);byte[] actual=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();return MessageDigest.isEqual(actual,expected)?r.getString(1)+"|"+r.getString(2):null;}}}
  synchronized List<UserRow> users() throws SQLException {List<UserRow> out=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement("SELECT username,full_name,profile,active,email,COALESCE(creci,'') FROM app_users ORDER BY full_name");ResultSet r=p.executeQuery()){while(r.next())out.add(new UserRow(r.getString(1),r.getString(2),r.getString(3),r.getInt(4)==1,r.getString(5),r.getString(6)));}return out;}
  synchronized void updateUser(String username,String profile,boolean active)throws SQLException{if(!Set.of("Administrador","Corretor","Atendimento").contains(profile))throw new IllegalArgumentException("Perfil inválido");try(PreparedStatement p=connection.prepareStatement("UPDATE app_users SET profile=?,active=? WHERE username=?")){p.setString(1,profile);p.setInt(2,active?1:0);p.setString(3,username);p.executeUpdate();}}
  synchronized List<RecordRow> records(String type)throws SQLException{List<RecordRow> out=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement("SELECT entity_type,entity_id,payload_json,version FROM local_records WHERE entity_type=? AND deleted=0 ORDER BY entity_id")){p.setString(1,type);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new RecordRow(r.getString(1),r.getString(2),r.getString(3),r.getLong(4)));}}return out;}
  synchronized void deleteRecord(String type,String id)throws SQLException{String now=Instant.now().toString();long base=0;try(PreparedStatement q=connection.prepareStatement("SELECT version FROM local_records WHERE entity_type=? AND entity_id=?")){q.setString(1,type);q.setString(2,id);try(ResultSet r=q.executeQuery()){if(r.next())base=r.getLong(1);}}try(PreparedStatement p=connection.prepareStatement("UPDATE local_records SET deleted=1,updated_at=? WHERE entity_type=? AND entity_id=?")){p.setString(1,now);p.setString(2,type);p.setString(3,id);p.executeUpdate();}try(PreparedStatement p=connection.prepareStatement("INSERT INTO sync_queue(entity_type,entity_id,operation,payload_json,base_version,created_at) VALUES(?,?,?,?,?,?)")){p.setString(1,type);p.setString(2,id);p.setString(3,"DELETE");p.setString(4,"{}");p.setLong(5,base);p.setString(6,now);p.executeUpdate();}}
  synchronized void upsert(String type,String id,String json)throws SQLException{String now=Instant.now().toString();long base=0;try(PreparedStatement q=connection.prepareStatement("SELECT version FROM local_records WHERE entity_type=? AND entity_id=?")){q.setString(1,type);q.setString(2,id);try(ResultSet r=q.executeQuery()){if(r.next())base=r.getLong(1);}}try(PreparedStatement p=connection.prepareStatement("INSERT INTO local_records(entity_type,entity_id,payload_json,version,updated_at,deleted) VALUES(?,?,?, ?,?,0) ON CONFLICT(entity_type,entity_id) DO UPDATE SET payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted=0")){p.setString(1,type);p.setString(2,id);p.setString(3,json);p.setLong(4,base);p.setString(5,now);p.executeUpdate();}try(PreparedStatement p=connection.prepareStatement("INSERT INTO sync_queue(entity_type,entity_id,operation,payload_json,base_version,created_at) VALUES(?,?,?,?,?,?)")){p.setString(1,type);p.setString(2,id);p.setString(3,"UPSERT");p.setString(4,json);p.setLong(5,base);p.setString(6,now);p.executeUpdate();}}
  synchronized long enqueueImage(String category,String entityId,String original,String staged)throws SQLException{try(PreparedStatement p=connection.prepareStatement("INSERT INTO image_queue(category,entity_id,original_name,staged_path,created_at) VALUES(?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,category);p.setString(2,entityId);p.setString(3,original);p.setString(4,staged);p.setString(5,Instant.now().toString());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())return r.getLong(1);}}throw new SQLException("Não foi possível registrar imagem");}
  synchronized List<ImageRow> pendingImages()throws SQLException{List<ImageRow> out=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement("SELECT id,category,entity_id,original_name,staged_path FROM image_queue WHERE status='PENDING' ORDER BY id");ResultSet r=p.executeQuery()){while(r.next())out.add(new ImageRow(r.getLong(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5)));}return out;}
  synchronized void markImageUploaded(long id)throws SQLException{try(PreparedStatement p=connection.prepareStatement("UPDATE image_queue SET status='UPLOADED',uploaded_at=? WHERE id=?")){p.setString(1,Instant.now().toString());p.setLong(2,id);p.executeUpdate();}}
  synchronized void markImageFailed(long id,String error)throws SQLException{try(PreparedStatement p=connection.prepareStatement("UPDATE image_queue SET status='PENDING',error_message=? WHERE id=?")){p.setString(1,error);p.setLong(2,id);p.executeUpdate();}}
  synchronized void applyRemote(String type,String id,String json,long version)throws SQLException{String now=Instant.now().toString();try(PreparedStatement p=connection.prepareStatement("INSERT INTO local_records(entity_type,entity_id,payload_json,version,updated_at,deleted) VALUES(?,?,?,?,?,0) ON CONFLICT(entity_type,entity_id) DO UPDATE SET payload_json=excluded.payload_json,version=excluded.version,updated_at=excluded.updated_at,deleted=0")){p.setString(1,type);p.setString(2,id);p.setString(3,json);p.setLong(4,version);p.setString(5,now);p.executeUpdate();}}
  synchronized void deleteRemote(String type,String id,long version)throws SQLException{String now=Instant.now().toString();try(PreparedStatement p=connection.prepareStatement("INSERT INTO local_records(entity_type,entity_id,payload_json,version,updated_at,deleted) VALUES(?,?,?, ?,?,1) ON CONFLICT(entity_type,entity_id) DO UPDATE SET version=excluded.version,updated_at=excluded.updated_at,deleted=1")){p.setString(1,type);p.setString(2,id);p.setString(3,"{}");p.setLong(4,version);p.setString(5,now);p.executeUpdate();}}
  synchronized void markSyncing()throws SQLException{try(Statement s=connection.createStatement()){s.executeUpdate("UPDATE sync_queue SET status='PENDING' WHERE status='SYNCING'");s.executeUpdate("UPDATE sync_queue SET status='SYNCING' WHERE id IN (SELECT id FROM sync_queue WHERE status='PENDING' ORDER BY id LIMIT 50)");}}
  synchronized String pendingJson()throws SQLException{StringBuilder b=new StringBuilder("[");boolean first=true;try(PreparedStatement p=connection.prepareStatement("SELECT id,entity_type,entity_id,operation,payload_json,base_version FROM sync_queue WHERE status='SYNCING' ORDER BY id LIMIT 50");ResultSet r=p.executeQuery()){while(r.next()){if(!first)b.append(',');first=false;b.append("{\"queueId\":").append(r.getLong(1)).append(",\"entityType\":\"").append(Main.esc(r.getString(2))).append("\",\"entityId\":\"").append(Main.esc(r.getString(3))).append("\",\"operation\":\"").append(Main.esc(r.getString(4))).append("\",\"payload\":").append(r.getString(5)).append(",\"baseVersion\":").append(r.getLong(6)).append('}');}}return b.append(']').toString();}
  synchronized void markSynced()throws SQLException{try(PreparedStatement p=connection.prepareStatement("UPDATE sync_queue SET status='SYNCED',synced_at=? WHERE status='SYNCING'")){p.setString(1,Instant.now().toString());p.executeUpdate();}}
  synchronized void markFailed(String reason)throws SQLException{try(PreparedStatement p=connection.prepareStatement("UPDATE sync_queue SET status='PENDING',error_message=? WHERE status='SYNCING'")){p.setString(1,reason);p.executeUpdate();}}
  synchronized String meta(String key)throws SQLException{try(PreparedStatement p=connection.prepareStatement("SELECT value FROM app_meta WHERE key=?")){p.setString(1,key);try(ResultSet r=p.executeQuery()){return r.next()?r.getString(1):null;}}}
  synchronized void setMeta(String key,String value)throws SQLException{try(PreparedStatement p=connection.prepareStatement("INSERT INTO app_meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value")){p.setString(1,key);p.setString(2,value);p.executeUpdate();}}
  @Override public synchronized void close()throws SQLException{connection.close();}
}
