package com.wfcimoveis.wfcsystem;

import com.google.gson.*;
import javax.swing.*;
import java.awt.*;
import java.net.CookieManager;
import java.net.CookiePolicy;
import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public final class Main {
  static final Properties C=new Properties(); static final CookieManager CM=new CookieManager(null,CookiePolicy.ACCEPT_ALL); static final HttpClient HTTP=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).cookieHandler(CM).build();
  static JFrame frame; static String user=""; static AppDatabase DB; static CredentialVault VAULT=new CredentialVault(); static ImageStaging IMAGES; static ScheduledExecutorService SYNC; static JLabel syncLabel;
  public static void main(String[] a){SwingUtilities.invokeLater(()->{load();try{DB=new AppDatabase();IMAGES=new ImageStaging(DB);}catch(Exception e){msg(null,"Falha ao preparar dados locais: "+e.getMessage(),JOptionPane.ERROR_MESSAGE);return;}loginScreen();});}
  static void load(){try(var i=Main.class.getResourceAsStream("/config.properties.example")){if(i!=null)C.load(i);}catch(Exception ignored){}try(var i=Files.newInputStream(java.nio.file.Path.of("config.properties"))){C.load(i);}catch(Exception ignored){}}
  static void loginScreen(){frame=new JFrame(v("app.name","WFCSystem v1")+" — Login");frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);frame.setSize(480,360);frame.setLocationRelativeTo(null);JPanel p=new JPanel(new BorderLayout(10,10));p.setBorder(BorderFactory.createEmptyBorder(18,22,18,22));JLabel t=new JLabel("Acesso ao sistema",SwingConstants.CENTER);t.setFont(new Font(Font.SANS_SERIF,Font.BOLD,20));p.add(t,BorderLayout.NORTH);JPanel f=new JPanel(new GridLayout(6,1,6,6));JTextField id=new JTextField("wellington.wfc");JPasswordField pw=new JPasswordField();f.add(new JLabel("Username cadastrado"));f.add(id);f.add(new JLabel("Senha"));f.add(pw);JButton b=new JButton("Entrar online"),offline=new JButton("Entrar offline");f.add(b);f.add(offline);p.add(f,BorderLayout.CENTER);p.add(new JLabel("Banco local: "+DB.path(),SwingConstants.CENTER),BorderLayout.SOUTH);frame.setContentPane(p);frame.setVisible(true);b.addActionListener(e->login(id.getText().trim(),new String(pw.getPassword())));offline.addActionListener(e->localLogin(id.getText().trim(),new String(pw.getPassword())));pw.addActionListener(e->b.doClick());}
  static void localLogin(String id,String pw){if(id.isBlank()||pw.isBlank()){msg(frame,"Informe o username e a senha.",JOptionPane.WARNING_MESSAGE);return;}try{String result=DB.authenticateLocal(id,pw.toCharArray());if(result==null){msg(frame,"Acesso offline negado.",JOptionPane.ERROR_MESSAGE);return;}user=result.split("\\|",2)[0]+" — "+result.split("\\|",2)[1];home();}catch(Exception e){msg(frame,e.getMessage(),JOptionPane.ERROR_MESSAGE);}}
  static void login(String id,String pw){if(id.isBlank()||pw.isBlank()){msg(frame,"Informe o username e a senha.",JOptionPane.WARNING_MESSAGE);return;}try{HttpResponse<String> h=HTTP.send(HttpRequest.newBuilder(URI.create(api()+"/health")).timeout(Duration.ofSeconds(15)).GET().build(),HttpResponse.BodyHandlers.ofString());if(h.statusCode()!=200){localFallback(id,pw,"API indisponível. HTTP "+h.statusCode());return;}String body="{\"identity\":\""+esc(id)+"\",\"password\":\""+esc(pw)+"\"}";HttpResponse<String> r=HTTP.send(HttpRequest.newBuilder(URI.create(api()+"/auth/login")).timeout(Duration.ofSeconds(20)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()>=200&&r.statusCode()<300&&r.body().contains("\"user\"")){user=jval(r.body(),"name",id);home();}else msg(frame,jval(r.body(),"error","Login não autorizado."),JOptionPane.ERROR_MESSAGE);}catch(Exception e){localFallback(id,pw,"Não foi possível conectar à API.");}}
  static void localFallback(String id,String pw,String reason){try{String result=DB.authenticateLocal(id,pw.toCharArray());if(result!=null){String[] p=result.split("\\|",2);user=p[0]+" — "+p[1];home();}else msg(frame,reason+"\nAcesso local negado.",JOptionPane.ERROR_MESSAGE);}catch(Exception e){msg(frame,reason,JOptionPane.ERROR_MESSAGE);}}
  static void home(){frame.getContentPane().removeAll();frame.setJMenuBar(menu());frame.setTitle(v("app.name","WFCSystem v1")+" — "+user);JPanel p=new JPanel(new BorderLayout(8,8));p.setBorder(BorderFactory.createEmptyBorder(8,8,8,8));p.add(new ManagementPanel(DB,IMAGES),BorderLayout.CENTER);JPanel bottom=new JPanel(new FlowLayout(FlowLayout.LEFT));syncLabel=new JLabel("Sincronização: aguardando");JButton sync=new JButton("Sincronizar agora");sync.addActionListener(e->syncNow(true));bottom.add(sync);bottom.add(syncLabel);bottom.add(new JLabel("Temporários: "+IMAGES.root()));p.add(bottom,BorderLayout.SOUTH);frame.setContentPane(p);frame.setExtendedState(JFrame.MAXIMIZED_BOTH);frame.setVisible(true);startSync();}
  static JMenuBar menu(){JMenuBar bar=new JMenuBar();JMenu cfg=new JMenu("Configurações");JMenuItem credentials=new JMenuItem("Credenciais criptografadas");credentials.addActionListener(e->credentialsDialog());cfg.add(credentials);JMenuItem ftp=new JMenuItem("Testar FTP e enviar imagens pendentes");ftp.addActionListener(e->syncNow(true));cfg.add(ftp);bar.add(cfg);JMenu out=new JMenu("Sair");out.addMenuListener(new javax.swing.event.MenuListener(){public void menuSelected(javax.swing.event.MenuEvent e){logout();}public void menuDeselected(javax.swing.event.MenuEvent e){}public void menuCanceled(javax.swing.event.MenuEvent e){}});bar.add(out);return bar;}
  static void credentialsDialog(){String[] names={"cpanel.url","cpanel.username","cpanel.password","ftp.host","ftp.port","ftp.username","ftp.password","phpmyadmin.url","phpmyadmin.username","phpmyadmin.password","mysql.host","mysql.database"};char[] pass;if(VAULT.exists()){JPasswordField unlock=new JPasswordField();if(JOptionPane.showConfirmDialog(frame,unlock,"Senha-mestra do cofre",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;pass=unlock.getPassword();try{VAULT.load(pass);}catch(Exception e){msg(frame,"Senha-mestra inválida ou cofre corrompido.",JOptionPane.ERROR_MESSAGE);return;}}else{JPasswordField create=new JPasswordField();if(JOptionPane.showConfirmDialog(frame,create,"Crie uma senha-mestra com pelo menos 8 caracteres",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;pass=create.getPassword();if(pass.length<8){msg(frame,"A senha-mestra deve ter pelo menos 8 caracteres.",JOptionPane.WARNING_MESSAGE);return;}}JPanel p=new JPanel(new GridLayout(0,2,6,6));JTextField[] fields=new JTextField[names.length];for(int i=0;i<names.length;i++){p.add(new JLabel(names[i]));fields[i]=names[i].contains("password")?new JPasswordField():new JTextField();fields[i].setText(VAULT.get(names[i]));p.add(fields[i]);}if(JOptionPane.showConfirmDialog(frame,p,"Credenciais criptografadas",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;try{for(int i=0;i<names.length;i++)VAULT.put(names[i],fields[i].getText());VAULT.save(pass);msg(frame,"Cofre salvo localmente.",JOptionPane.INFORMATION_MESSAGE);}catch(Exception e){msg(frame,"Falha ao salvar cofre.",JOptionPane.ERROR_MESSAGE);}}
  static void startSync(){if(SYNC!=null)SYNC.shutdownNow();SYNC=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"wfc-sync");t.setDaemon(true);return t;});SYNC.scheduleWithFixedDelay(()->syncNow(false),10,60,TimeUnit.SECONDS);}
  static void syncNow(boolean interactive){try{DB.markSyncing();String payload=DB.pendingJson();if(!payload.equals("[]")){HttpResponse<String> r=HTTP.send(HttpRequest.newBuilder(URI.create(api()+"/sync/push")).timeout(Duration.ofSeconds(30)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString("{\"items\":"+payload+"}")).build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()<200||r.statusCode()>=300)throw new IllegalStateException("API de envio HTTP "+r.statusCode());JsonObject pushed=JsonParser.parseString(r.body()).getAsJsonObject();if(pushed.has("conflicts")&&!pushed.getAsJsonArray("conflicts").isEmpty())throw new IllegalStateException("Existem conflitos no servidor; nenhuma alteração conflitante foi apagada.");DB.markSynced();}pullChanges();uploadImages();setSync("Online — sincronizado");}catch(Exception e){try{DB.markFailed(e.getMessage());}catch(Exception ignored){}setSync("Offline — pendências preservadas");if(interactive)msg(frame,"Não foi possível concluir a sincronização. Os dados e imagens continuam preservados localmente.\n"+e.getMessage(),JOptionPane.WARNING_MESSAGE);}}
  static void pullChanges()throws Exception{String since=DB.meta("last_sync_at");if(since==null)since="";String url=api()+"/sync/pull?since="+java.net.URLEncoder.encode(since,StandardCharsets.UTF_8);HttpResponse<String> r=HTTP.send(HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(30)).GET().build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()==404)return;if(r.statusCode()<200||r.statusCode()>=300)throw new IllegalStateException("API de recebimento HTTP "+r.statusCode());JsonObject root=JsonParser.parseString(r.body()).getAsJsonObject();for(JsonElement e:root.getAsJsonArray("items")){JsonObject item=e.getAsJsonObject();String type=item.get("entityType").getAsString(),id=item.get("entityId").getAsString(),op=item.has("operation")?item.get("operation").getAsString():"UPSERT";long version=item.get("version").getAsLong();if("DELETE".equals(op))DB.deleteRemote(type,id,version);else DB.applyRemote(type,id,item.get("payload").toString(),version);}if(root.has("serverTime"))DB.setMeta("last_sync_at",root.get("serverTime").getAsString());}
  static void uploadImages()throws Exception{if(IMAGES.pending().isEmpty())return;String host=VAULT.get("ftp.host");if(host.isBlank())host=v("ftp.host","");String portText=VAULT.get("ftp.port");if(portText.isBlank())portText=v("ftp.port","21");String username=VAULT.get("ftp.username");String password=VAULT.get("ftp.password");String properties=v("ftp.propertiesPath","/public_html/wfc_storage/wfc_imoveis"), testimonials=v("ftp.testimonialsPath","/public_html/wfc_storage/nossos_clientes/prova_social");IMAGES.uploadPending(host,Integer.parseInt(portText),username,password,properties,testimonials);}
  static void setSync(String s){SwingUtilities.invokeLater(()->{if(syncLabel!=null)syncLabel.setText("Sincronização: "+s);});}
  static void logout(){try{HTTP.send(HttpRequest.newBuilder(URI.create(api()+"/auth/logout")).POST(HttpRequest.BodyPublishers.noBody()).build(),HttpResponse.BodyHandlers.ofString());}catch(Exception ignored){}if(SYNC!=null)SYNC.shutdownNow();CM.getCookieStore().removeAll();frame.dispose();loginScreen();}
  static String api(){return v("api.baseUrl","https://wfcimoveis.com/sistema/api/v1").replaceAll("/$","");}static String v(String k,String d){return C.getProperty(k,d);}static String esc(String x){return x.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}static String jval(String j,String k,String d){Matcher m=Pattern.compile("\\\""+Pattern.quote(k)+"\\\"\\s*:\\s*\\\"([^\\\"]*)").matcher(j);return m.find()?m.group(1):d;}static void msg(Component c,String x,int t){JOptionPane.showMessageDialog(c,x,"WFCSystem v1",t);}
}
