package com.wfcimoveis.wfcsystem;

import javax.swing.*;
import java.awt.*;
import java.net.CookieManager;
import java.net.CookiePolicy;
import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public final class Main {
  static final Properties C=new Properties();
  static final CookieManager CM=new CookieManager(null,CookiePolicy.ACCEPT_ALL);
  static final HttpClient HTTP=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).cookieHandler(CM).build();
  static JFrame frame; static String user=""; static AppDatabase DB; static CredentialVault VAULT=new CredentialVault(); static ScheduledExecutorService SYNC; static JLabel syncLabel;
  public static void main(String[] a){SwingUtilities.invokeLater(()->{load();try{DB=new AppDatabase();}catch(Exception e){msg(null,"Falha ao abrir banco SQLite local: "+e.getMessage(),JOptionPane.ERROR_MESSAGE);return;}loginScreen();});}
  static void load(){try(var i=Main.class.getResourceAsStream("/config.properties.example")){if(i!=null)C.load(i);}catch(Exception ignored){}try(var i=java.nio.file.Files.newInputStream(java.nio.file.Path.of("config.properties"))){C.load(i);}catch(Exception ignored){}}
  static void loginScreen(){frame=new JFrame(v("app.name","WFCSystem v1")+" — Login");frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);frame.setSize(480,360);frame.setLocationRelativeTo(null);JPanel p=new JPanel(new BorderLayout(10,10));p.setBorder(BorderFactory.createEmptyBorder(18,22,18,22));JLabel t=new JLabel("Acesso ao sistema",SwingConstants.CENTER);t.setFont(new Font(Font.SANS_SERIF,Font.BOLD,20));p.add(t,BorderLayout.NORTH);JPanel f=new JPanel(new GridLayout(6,1,6,6));JTextField id=new JTextField("wellington.wfc");JPasswordField pw=new JPasswordField();f.add(new JLabel("Username cadastrado"));f.add(id);f.add(new JLabel("Senha"));f.add(pw);JButton b=new JButton("Entrar online");JButton offline=new JButton("Entrar offline");f.add(b);f.add(offline);p.add(f,BorderLayout.CENTER);p.add(new JLabel("Banco local: "+DB.path(),SwingConstants.CENTER),BorderLayout.SOUTH);frame.setContentPane(p);frame.setVisible(true);b.addActionListener(e->login(id.getText().trim(),new String(pw.getPassword())));offline.addActionListener(e->localLogin(id.getText().trim(),new String(pw.getPassword())));pw.addActionListener(e->b.doClick());id.requestFocusInWindow();}
  static void localLogin(String id,String pw){if(id.isBlank()||pw.isBlank()){msg(frame,"Informe o username cadastrado e a senha.",JOptionPane.WARNING_MESSAGE);return;}try{String result=DB.authenticateLocal(id,pw.toCharArray());if(result==null){msg(frame,"Acesso offline negado. Usuário não cadastrado, inativo ou senha inválida.",JOptionPane.ERROR_MESSAGE);return;}String[] parts=result.split("\\|",2);user=parts[0]+" — "+parts[1]+" (offline)";home();}catch(Exception e){msg(frame,"Falha ao validar usuário local: "+e.getMessage(),JOptionPane.ERROR_MESSAGE);}}
  static void login(String id,String pw){if(id.isBlank()||pw.isBlank()){msg(frame,"Informe o username cadastrado e a senha.",JOptionPane.WARNING_MESSAGE);return;}String base=api();try{HttpResponse<String> h=HTTP.send(HttpRequest.newBuilder(URI.create(base+"/health")).timeout(Duration.ofSeconds(15)).GET().build(),HttpResponse.BodyHandlers.ofString());if(h.statusCode()!=200){localFallback(id,pw,"API indisponível. HTTP "+h.statusCode());return;}String body="{\"identity\":\""+esc(id)+"\",\"password\":\""+esc(pw)+"\"}";HttpRequest q=HttpRequest.newBuilder(URI.create(base+"/auth/login")).timeout(Duration.ofSeconds(20)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body)).build();HttpResponse<String> r=HTTP.send(q,HttpResponse.BodyHandlers.ofString());if(r.statusCode()>=200&&r.statusCode()<300&&r.body().contains("\"user\"")){user=jval(r.body(),"name",id);home();}else msg(frame,jval(r.body(),"error","Login não autorizado.")+"\nHTTP "+r.statusCode(),JOptionPane.ERROR_MESSAGE);}catch(Exception e){localFallback(id,pw,"Não foi possível conectar à API: "+e.getMessage());}}
  static void localFallback(String id,String pw,String reason){try{String result=DB.authenticateLocal(id,pw.toCharArray());if(result!=null){String[] parts=result.split("\\|",2);user=parts[0]+" — "+parts[1]+" (offline)";home();}else msg(frame,reason+"\nAcesso local negado: usuário não cadastrado ou senha inválida.",JOptionPane.ERROR_MESSAGE);}catch(Exception e){msg(frame,reason+"\nFalha ao validar cadastro local.",JOptionPane.ERROR_MESSAGE);}}
  static void home(){frame.getContentPane().removeAll();frame.setJMenuBar(menu());frame.setTitle(v("app.name","WFCSystem v1")+" — "+user);JPanel p=new JPanel(new BorderLayout(12,12));p.setBorder(BorderFactory.createEmptyBorder(24,24,24,24));JLabel w=new JLabel("Olá, "+user);w.setFont(new Font(Font.SANS_SERIF,Font.BOLD,18));p.add(w,BorderLayout.NORTH);JTextArea info=new JTextArea("WFCSystem v1\n\nBanco local SQLite ativo.\nDados operacionais podem ser usados offline e sincronizados quando a API estiver disponível.\n\nArquivo local: "+DB.path());info.setEditable(false);info.setOpaque(false);info.setFont(new Font(Font.SANS_SERIF,Font.PLAIN,14));p.add(info,BorderLayout.CENTER);JPanel a=new JPanel(new FlowLayout(FlowLayout.LEFT));syncLabel=new JLabel("Sincronização: aguardando");JButton sync=new JButton("Sincronizar agora");sync.addActionListener(e->syncNow(true));a.add(sync);a.add(syncLabel);p.add(a,BorderLayout.SOUTH);frame.setContentPane(p);frame.setSize(800,500);frame.setLocationRelativeTo(null);frame.revalidate();frame.repaint();startSync();}
  static JMenuBar menu(){JMenuBar bar=new JMenuBar();for(String x:new String[]{"Início","Imóveis","Clientes","Agentes","Vendas"})bar.add(new JMenu(x));JMenu cfg=new JMenu("Configurações");JMenuItem credentials=new JMenuItem("Credenciais criptografadas");credentials.addActionListener(e->credentialsDialog());JMenuItem local=new JMenuItem("Registrar dado local");local.addActionListener(e->localRecordDialog());cfg.add(credentials);cfg.add(local);bar.add(cfg);JMenu out=new JMenu("Sair");out.addMenuListener(new javax.swing.event.MenuListener(){public void menuSelected(javax.swing.event.MenuEvent e){logout();}public void menuDeselected(javax.swing.event.MenuEvent e){}public void menuCanceled(javax.swing.event.MenuEvent e){}});bar.add(out);return bar;}
  static void credentialsDialog(){String[] names={"cpanel.url","cpanel.username","cpanel.password","ftp.host","ftp.port","ftp.username","ftp.password","phpmyadmin.url","phpmyadmin.username","phpmyadmin.password","mysql.host","mysql.database"};char[] pass;if(VAULT.exists()){JPasswordField unlock=new JPasswordField();if(JOptionPane.showConfirmDialog(frame,unlock,"Senha-mestra do cofre",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;pass=unlock.getPassword();try{VAULT.load(pass);}catch(Exception e){msg(frame,"Não foi possível abrir o cofre: senha inválida ou arquivo corrompido.",JOptionPane.ERROR_MESSAGE);return;}}else{JPasswordField create=new JPasswordField();if(JOptionPane.showConfirmDialog(frame,create,"Crie uma senha-mestra com pelo menos 8 caracteres",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;pass=create.getPassword();if(pass.length<8){msg(frame,"A senha-mestra deve ter pelo menos 8 caracteres.",JOptionPane.WARNING_MESSAGE);return;}}JPanel p=new JPanel(new GridLayout(0,2,6,6));JTextField[] fields=new JTextField[names.length];for(int i=0;i<names.length;i++){p.add(new JLabel(names[i]));fields[i]=names[i].contains("password")?new JPasswordField():new JTextField();fields[i].setText(VAULT.get(names[i]));p.add(fields[i]);}JPanel all=new JPanel(new BorderLayout(8,8));all.add(new JLabel("Credenciais criptografadas localmente; nunca são enviadas para logs ou para o Git."),BorderLayout.NORTH);all.add(p,BorderLayout.CENTER);if(JOptionPane.showConfirmDialog(frame,all,"Configuração de credenciais",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return;try{for(int i=0;i<names.length;i++)VAULT.put(names[i],fields[i].getText());VAULT.save(pass);msg(frame,"Cofre salvo com criptografia AES-GCM em ~/.wfcsystem.",JOptionPane.INFORMATION_MESSAGE);}catch(Exception e){msg(frame,"Não foi possível salvar o cofre: "+e.getMessage(),JOptionPane.ERROR_MESSAGE);}}
  static void localRecordDialog(){JTextField type=new JTextField("imovel"),id=new JTextField(),json=new JTextField("{}");JPanel p=new JPanel(new GridLayout(0,2,6,6));p.add(new JLabel("Tipo"));p.add(type);p.add(new JLabel("ID"));p.add(id);p.add(new JLabel("JSON"));p.add(json);if(JOptionPane.showConfirmDialog(frame,p,"Registrar alteração local",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION)try{if(id.getText().isBlank())throw new IllegalArgumentException("ID obrigatório");DB.upsert(type.getText(),id.getText(),json.getText());syncNow(false);}catch(Exception e){msg(frame,e.getMessage(),JOptionPane.ERROR_MESSAGE);}}
  static void startSync(){if(SYNC!=null)SYNC.shutdownNow();SYNC=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"wfc-sync");t.setDaemon(true);return t;});SYNC.scheduleWithFixedDelay(()->syncNow(false),10,60,TimeUnit.SECONDS);}
  static void syncNow(boolean interactive){try{DB.markSyncing();String payload=DB.pendingJson();if(!payload.equals("[]")){HttpRequest q=HttpRequest.newBuilder(URI.create(api()+"/sync/push")).timeout(Duration.ofSeconds(30)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString("{\"items\":"+payload+"}")).build();HttpResponse<String> r=HTTP.send(q,HttpResponse.BodyHandlers.ofString());if(r.statusCode()<200||r.statusCode()>=300){DB.markFailed("HTTP "+r.statusCode());throw new IllegalStateException("API de envio HTTP "+r.statusCode());}DB.markSynced();}String since=DB.meta("last_sync_at");if(since==null)since="";HttpRequest pull=HttpRequest.newBuilder(URI.create(api()+"/sync/pull?since="+java.net.URLEncoder.encode(since,StandardCharsets.UTF_8))).timeout(Duration.ofSeconds(30)).GET().build();HttpResponse<String> pr=HTTP.send(pull,HttpResponse.BodyHandlers.ofString());if(pr.statusCode()>=200&&pr.statusCode()<300){Pattern item=Pattern.compile("\\{\\\"entityType\\\":\\\"([^\\\"]+)\\\",\\\"entityId\\\":\\\"([^\\\"]+)\\\",\\\"version\\\":(\\d+),\\\"payload\\\":(\\{.*?\\})\\}");Matcher m=item.matcher(pr.body());while(m.find())DB.applyRemote(m.group(1),m.group(2),m.group(4),Long.parseLong(m.group(3)));DB.setMeta("last_sync_at",java.time.Instant.now().toString());setSync("Sincronizado às "+java.time.LocalTime.now().withNano(0));}else if(pr.statusCode()!=404){throw new IllegalStateException("API de recebimento HTTP "+pr.statusCode());}else setSync("Envio concluído; API ainda sem endpoint de recebimento");}catch(Exception e){try{DB.markFailed(e.getMessage());}catch(Exception ignored){}setSync("Offline — pendências preservadas localmente");if(interactive)msg(frame,"Sem conexão ou API de sincronização indisponível; os dados permanecem no SQLite e serão reenviados automaticamente.\n"+e.getMessage(),JOptionPane.WARNING_MESSAGE);}}
  static void setSync(String s){SwingUtilities.invokeLater(()->{if(syncLabel!=null)syncLabel.setText("Sincronização: "+s);});}
  static void session(){try{HttpResponse<String> r=HTTP.send(HttpRequest.newBuilder(URI.create(api()+"/auth/me")).GET().build(),HttpResponse.BodyHandlers.ofString());msg(frame,r.statusCode()==200?"Sessão válida.":"Sessão expirada. HTTP "+r.statusCode(),r.statusCode()==200?JOptionPane.INFORMATION_MESSAGE:JOptionPane.WARNING_MESSAGE);}catch(Exception e){msg(frame,"Falha: "+e.getMessage(),JOptionPane.ERROR_MESSAGE);}}
  static void logout(){try{HTTP.send(HttpRequest.newBuilder(URI.create(api()+"/auth/logout")).POST(HttpRequest.BodyPublishers.noBody()).build(),HttpResponse.BodyHandlers.ofString());}catch(Exception ignored){}if(SYNC!=null)SYNC.shutdownNow();CM.getCookieStore().removeAll();frame.dispose();loginScreen();}
  static String api(){String x=v("api.baseUrl","https://wfcimoveis.com/sistema/api/v1").trim();return x.replaceAll("/$","");}static String v(String k,String d){return C.getProperty(k,d);}static String esc(String x){return x.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n");}static String jval(String j,String k,String d){Matcher m=Pattern.compile("\\\""+Pattern.quote(k)+"\\\"\\s*:\\s*\\\"([^\\\"]*)").matcher(j);return m.find()?m.group(1):d;}static void msg(Component c,String x,int t){JOptionPane.showMessageDialog(c,x,"WFCSystem v1",t);}
}
